# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Michael Dorrance"
description: > # this means to ignore newlines until "email:"
   Coding Carpenter

email: mike@neuvocreate.com
#blog logo
logo: "/assets/images/hammer_black_300.jpg"
# blog cover
cover: "/assets/images/mac_on_table_web_2000.jpg"

name: 'Michael Dorrance'
author: 'Michael Dorrance'
author_image: "/assets/images/michael_dorrance_bw_web.jpg"

paginate:	5

url: "http://mdorrance.github.io/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dorrancemike
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/mdorrance
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
